export const SET_CRYPTO_DATA = 'SET_CRYPTO_DATA';
export const SET_ACTIVE_CRYPTO_CURRENCY = 'SET_CRYPTO_CURRENCY_INDEX';
export const SET_INPUT = 'SET_INPUT';
export const SET_ACTIVE_CURRENCY_EXCHANGE = 'SET_ACTIVE_CURRENCY_EXCHANGE';
